--- 
grid_map_topic: /pedsim_demo/grid_map
grid_map_visualizations:
  #- name: elevation_points
    #type: point_cloud
    #params:
     #layer: elevation
  #- name: elevation_grid
    #type: occupancy_grid
    #params:
     #layer: elevation
     #data_min: 0.08
     #data_max: -0.16
  - name: map_region
    type: map_region
    params:
      color: 0000230
      line_width: 1
